### PR TITLE
Feature/dam 21

### PR DESCRIPTION
**Pull request by jsbarbergit**

### CODE REVIEW

**Comment by jsbarbergit** [comment]
Comments from initial show and tell call to be worked on:
- Apply standard naming convention to EFS volumes
- Add cloudwatch log lifecycle options to task definitions
- Restrict overly permissive outbound sec groups
- Add tag propagation from ecs nodes to task defs

**Comment by jsbarbergit** [comment]
- No longer using ebs volumes, will use relocatable ebs volume, but naming policy applied to those volumes now.
- awslogs driver doesn't include cloudwatch log retention values, so switched to manage the groups in terraform
- tags cannot be propagated to tasks until the new ARN and resource if format. TF code added but commented out for now as unknown impact of globally accepting new arn and resource id format

**Comment by jsbarbergit** [comment]
egress security groups tightened up. just waiting on resolving an issue with pulling remote ecr image before adding reviewers and getting merged

**Review by smjmoj — APPROVED** [review]
Looks good, thoroughly explained during code review session.
Team comments applied.

**Review by marcus-bcl — APPROVED** [review]

**Review by enyambudzi — APPROVED** [review]

**Pull request merged**
